<?php

declare(strict_types=1);

namespace App\Index;

use App\Index\Repository\EpsteinRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity from profile
 * @profile data/epstein.profile.json
 */
#[Entity(repositoryClass: EpsteinRepository::class)]
#[MeiliIndex(
	primaryKey: 'id',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Epstein
{
	public const FILTERABLE_FIELDS = ['dirname', 'extension', 'tags', 'probeLevel'];
	public const SORTABLE_FIELDS = [];
	public const SEARCHABLE_FIELDS = [];

	/**
	 * Profile field "id"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=4192
	 */
	#[Column(length: 16, nullable: false)]
	#[Id]
	public ?string $id = null;

	/**
	 * Profile field "path"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=4192
	 * @imageLike true
	 */
	#[Column(length: 134, nullable: true)]
	public ?string $path = null;

	/**
	 * Profile field "relative_path"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=4192
	 * @imageLike true
	 */
	#[Column(length: 66, nullable: true)]
	public ?string $relativePath = null;

	/**
	 * Profile field "filename"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=4192
	 * @imageLike true
	 */
	#[Column(length: 43, nullable: true)]
	public ?string $filename = null;

	/**
	 * Profile field "basename"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=4192
	 * @imageLike true
	 */
	#[Column(length: 43, nullable: true)]
	public ?string $basename = null;

	/**
	 * Profile field "dirname"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=13
	 */
	#[Column(length: 110, nullable: true)]
	public ?string $dirname = null;

	/**
	 * Profile field "extension"
	 * @types string (storageHint=string)
	 * @stats total=4192, nulls=0, distinct=3
	 */
	#[Column(length: 3, nullable: true)]
	public ?string $extension = null;

	/**
	 * Profile field "tags"
	 * @types array (storageHint=json)
	 * @stats total=4192, nulls=0, distinct=13
	 */
	#[Column(type: Types::JSON, nullable: false)]
	public array $tags = [];

	/**
	 * Profile field "probe_level"
	 * @types int (storageHint=int)
	 * @stats total=4192, nulls=0, distinct=1
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $probeLevel = null;
}
