<?php

declare(strict_types=1);

namespace App\Index;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use DateTimeImmutable;
use Survos\MeiliBundle\Metadata\MeiliIndex;
use Symfony\Component\Serializer\Attribute\Groups;

/**
 * @generated by code:entity from profile
 * @profile data/test_sample.profile.json
 */
#[ApiResource(operations: [
	new Get(normalizationContext: ["groups" => ["sample.read"]]),
	new GetCollection(normalizationContext: ["groups" => ["sample.read"]]),
])]
#[ApiFilter(filterClass: \ApiPlatform\Doctrine\Orm\Filter\SearchFilter::class, properties: self::FILTERABLE_FIELDS)]
#[ApiFilter(filterClass: \ApiPlatform\Doctrine\Orm\Filter\SearchFilter::class, properties: self::SEARCHABLE_FIELDS)]
#[ApiFilter(filterClass: \ApiPlatform\Doctrine\Orm\Filter\OrderFilter::class, properties: self::SORTABLE_FIELDS)]
#[MeiliIndex(
	primaryKey: 'id',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Sample
{
	public const FILTERABLE_FIELDS = [
		'rootPath',
		'dirname',
		'extension',
		'tags',
		'probeLevel',
		'mimeType',
		'createdTime',
		'modifiedTime',
		'isReadable',
		'duplicateOf',
	];

	public const SORTABLE_FIELDS = ['size'];
	public const SEARCHABLE_FIELDS = ['filename', 'basename'];

	/**
	 * Profile field "id"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=101
	 */
	#[ApiProperty(description: 'Profile field "id": types=[string], storageHint=string, distinct=101, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $id = null;

	/**
	 * Profile field "root_id"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=1
	 */
	#[ApiProperty(description: 'Profile field "root_id": types=[string], storageHint=string, distinct=1, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $rootId = null;

	/**
	 * Profile field "root_path"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=1
	 */
	#[ApiProperty(description: 'Profile field "root_path": types=[string], storageHint=string, distinct=1, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $rootPath = null;

	/**
	 * Profile field "path"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=101
	 */
	#[ApiProperty(description: 'Profile field "path": types=[string], storageHint=string, distinct=101, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $path = null;

	/**
	 * Profile field "relative_path"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=101
	 */
	#[ApiProperty(description: 'Profile field "relative_path": types=[string], storageHint=string, distinct=101, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $relativePath = null;

	/**
	 * Profile field "filename"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=85
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[ApiProperty(description: 'Profile field "filename": types=[string], storageHint=string, distinct=85, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $filename = null;

	/**
	 * Profile field "basename"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=85
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[ApiProperty(description: 'Profile field "basename": types=[string], storageHint=string, distinct=85, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $basename = null;

	/**
	 * Profile field "dirname"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=35
	 */
	#[ApiProperty(description: 'Profile field "dirname": types=[string], storageHint=string, distinct=35, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $dirname = null;

	/**
	 * Profile field "extension"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=10
	 */
	#[ApiProperty(description: 'Profile field "extension": types=[string], storageHint=string, distinct=10, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $extension = null;

	/**
	 * Profile field "tags"
	 * @types array (storageHint=json)
	 * @stats total=101, nulls=0, distinct=35
	 */
	#[ApiProperty(description: 'Profile field "tags": types=[array], storageHint=json, distinct=35, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public array $tags = [];

	/**
	 * Profile field "probe_level"
	 * @types int (storageHint=int)
	 * @stats total=101, nulls=0, distinct=1
	 */
	#[ApiProperty(description: 'Profile field "probe_level": types=[int], storageHint=int, distinct=1, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?int $probeLevel = null;

	/**
	 * Profile field "size"
	 * @types int (storageHint=int)
	 * @stats total=101, nulls=0, distinct=82
	 */
	#[ApiProperty(description: 'Profile field "size": types=[int], storageHint=int, distinct=82, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?int $size = null;

	/**
	 * Profile field "mime_type"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=10
	 */
	#[ApiProperty(description: 'Profile field "mime_type": types=[string], storageHint=string, distinct=10, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $mimeType = null;

	/**
	 * Profile field "created_time"
	 * @types int (storageHint=int)
	 * @stats total=101, nulls=0, distinct=2
	 */
	#[ApiProperty(description: 'Profile field "created_time": types=[int], storageHint=int, distinct=2, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?int $createdTime = null;

	/**
	 * Profile field "modified_time"
	 * @types int (storageHint=int)
	 * @stats total=101, nulls=0, distinct=2
	 */
	#[ApiProperty(description: 'Profile field "modified_time": types=[int], storageHint=int, distinct=2, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?int $modifiedTime = null;

	/**
	 * Profile field "is_readable"
	 * @types bool (storageHint=bool)
	 * @stats total=101, nulls=0, distinct=1
	 * @booleanLike true
	 */
	#[ApiProperty(description: 'Profile field "is_readable": types=[bool], storageHint=bool, distinct=1, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?bool $isReadable = null;

	/**
	 * Profile field "checksum_xxh3"
	 * @types string (storageHint=string)
	 * @stats total=101, nulls=0, distinct=95
	 */
	#[ApiProperty(description: 'Profile field "checksum_xxh3": types=[string], storageHint=string, distinct=95, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $checksumXxh3 = null;

	/**
	 * Profile field "duplicate_of"
	 * @types string (storageHint=string)
	 * @stats total=6, nulls=0, distinct=2
	 * @naturalLanguageLike true
	 */
	#[ApiProperty(description: 'Profile field "duplicate_of": types=[string], storageHint=string, distinct=2, nulls=0')]
	#[Groups(groups: ['sample.read'])]
	public ?string $duplicateOf = null;
}
