api_platform:
    title: KPA API
    version: 1.0.0

#    formats:
#        jsonld: ['application/ld+json']

    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']

    defaults:
        pagination_client_items_per_page: true
        pagination_enabled: true
        pagination_client_enabled: false
        # To allow partial pagination for all resource collections.
        # This improves performances by skipping the `COUNT` query.
        pagination_partial: false
        pagination_items_per_page: 40

        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
