# config/packages/api_platform.yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
#            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    defaults:
        pagination_client_items_per_page: true
        pagination_enabled: true
        pagination_client_enabled: false
        # To allow partial pagination for all resource collections.
        # This improves performances by skipping the `COUNT` query.
        pagination_partial: false
        pagination_items_per_page: 40
