easy_admin:
    site_name: KPA

    disabled_actions: ['delete', 'edit', 'new']
    list:
        actions: ['show']
    design:
        menu:
            - { label: 'Dashboard', route: 'app_homepage', icon: dashboard }
            - { entity: Song, icon: 'fas fa-music' }
            - { entity: Video, icon: 'fas fa-video' }
            - { entity: School, icon: 'fas fa-university' }

    entities:
        Song:
            class: App\Entity\Song
        School:
            class: App\Entity\School
        Video:
            class: App\Entity\Video
            list:
                fields:
                    - { property: 'youtubeUrl', type: 'url' }
                    - { property: 'title' }
