# https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md

# AWS S3 client used by the aws-backed storages below.
# Credentials/region come from .env.local (AWS_* vars).
services:
    Aws\S3\S3Client:
        arguments:
            - version: 'latest'
              region: '%env(AWS_S3_REGION)%'
              credentials:
                  key: '%env(AWS_ACCESS_KEY_ID)%'
                  secret: '%env(AWS_SECRET_ACCESS_KEY)%'

flysystem:
    storages:
        archive.storage:
            aws:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET)%'
                streamReads: true
                prefix: '%env(string:S3_STORAGE_PREFIX)%'

when@test:
    flysystem:
        storages:
            archive.storage:
                local:
                    directory: '%kernel.project_dir%/var/storage/s3-test'
