knpu_oauth2_client:
    clients:
        github:
            # must be "github" - it activates that type!
            type: github
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: oauth_connect_check
            redirect_params: { clientKey: github }  # MUST match the client key above
        facebook:
            # must be "facebook" - it activates that type!
            type: facebook
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_CLIENT_SECRET)%'
            redirect_route: oauth_connect_check
            redirect_params: { clientKey: facebook }  # MUST match the client key (not type, but usually the same)
            graph_api_version: v2.12
            use_state: true
