meilisearch:
  url: '%env(MEILISEARCH_URL)%' # URL of the Meilisearch server (mandatory)
  api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
  prefix: ''
  indices:
    # Define entities or documents that should be indexed to Meilisearch.
    # See https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data
    - name: song
      class: App\Entity\Song
      enable_serializer_groups: true
      settings:
        filterableAttributes:
          - year
          - title
        sortableAttributes:
          - year
          - title
