when@dev:
  survos_command:
    # could also add expose=true to a ClassAttribute, with security or something
    namespaces: [app, ff, grid]
  #    app: true
  #    project: true # isGranted('PROJECT_ADMIN') ??
