twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
#        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'bootstrap_5_layout.html.twig'
        - 'bootstrap_5_horizontal_layout.html.twig'

when@test:
    twig:
        strict_variables: true
