widgets:
    left:
        - type: close
        - icon: "fa-bug"
          text: "1.47"
          url: "https://github.com/<FOO>/issues?q=is%3Aissue%20state%3Aopen%20milestone%3A1.47"
          target: "_blank"
          title: "Open Milestone 1.47 Issues"
        - icon: "fa-code-pull-request"
          url: "https://github.com/<FOO>/pulls"
          target: "_blank"
          title: "Open Repository Pull Requests"
        - text: "#1240: [ADM] Fix PageSection CRUD priority field configuration"
          url: "https://github.com/<FOO>>/issues/1240"
          target: "_blank"
          expand: true
    right:
        - icon: "fa-globe"
          url: "/"
          title: "Go to Main Page"
        - icon: "fa-crown"
          url: "/admin/"
          title: "Open Admin Panel"
        - icon: "fa-database"
          url: "http://localhost:21440"
          target: "_blank"
          title: "Open Database Manager"
        - icon: "fa-envelope"
          url: "http://localhost:21540"
          target: "_blank"
          title: "Open Mailpit"
