# .symfony.local.yaml
workers:
  # built-in command that builds and watches front-end assets

#   built-in command that starts messenger consumer
  messenger_meili:
       cmd: ['symfony', 'console', 'messenger:consume', 'meili', '--limit=10', '--time-limit=60']
       watch: ['config', 'src', 'templates', 'vendor']
#  messenger_consume_resize:
#    cmd: ['symfony', 'console', 'messenger:consume', 'resize']
#    watch: ['config', 'src', 'templates', 'vendor']

#  messenger_consume_async: ~

  # you can also add your own custom commands
#  build_spa:
#    cmd: ['yarn', '--cwd', './spa/', 'dev']

