version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

###> meilisearch/search-bundle ###
  meilisearch:
    ports:
      - "7700"
###< meilisearch/search-bundle ###
