<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\LyricsRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\Facet;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity
 */
#[Entity(repositoryClass: LyricsRepository::class)]
#[MeiliIndex(
    ui: ['icon' => 'Lyrics'],
    primaryKey: 'code',
    persisted: ['code','parent','file','lyricsAsString','lyrics'],
    searchable: ['lyricsAsString'],
    embedders: ['small_lyrics','best_lyrics'],
)]
final class Lyrics
{
	#[Column(length: 255, nullable: true)]
	#[Id]
	public ?string $code = null;

	#[Column(length: 255, nullable: true)]
//    #[Facet()]
	public ?string $parent = null;

	#[Column(length: 255, nullable: true)]
	public ?string $file = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $lyrics = null;

    public string $lyricsAsString { get => join("\n", $this->lyrics); }
}
