<?php

namespace App\Controller\Admin;

use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminDashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use Survos\MeiliBundle\Controller\AbstractMeiliController;

/**
 * Generated by code:meili:admin
 */
#[AdminDashboard('/ez-meili', self::MEILI_ROUTE)]
final class MeiliDashboardController extends AbstractMeiliController
{
    public const MEILI_ROUTE = 'meili_admin';

    public function configureDashboard(): Dashboard
    {
        return parent::configureDashboard()
            ->setTitle('Meili Admin');
    }
}
