<?php

namespace App\Controller\Admin;

use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Survos\CoreBundle\Controller\BaseCrudController;

class SongCrudController extends BaseCrudController
{
    public static function getEntityFqcn(): string
    {
        return \App\Entity\Song::class;
    }

    public function configureFields(string $pageName): iterable
    {
        yield TextField::new('title');
        foreach (parent::configureFields($pageName) as $field) {
            yield $field;
        }// TODO: Change the autogenerated stub
    }
}
