<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616225523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT fk_77fe42f2727aca70');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT fk_77fe42f2f3ad3475');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('ALTER TABLE file_asset ADD s3 VARCHAR(512) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA toolkit_experimental');
        $this->addSql('CREATE SCHEMA timescaledb_information');
        $this->addSql('CREATE SCHEMA timescaledb_experimental');
        $this->addSql('CREATE SCHEMA _timescaledb_internal');
        $this->addSql('CREATE SCHEMA _timescaledb_functions');
        $this->addSql('CREATE SCHEMA _timescaledb_config');
        $this->addSql('CREATE SCHEMA _timescaledb_catalog');
        $this->addSql('CREATE SCHEMA _timescaledb_cache');
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE INDEX idx_77fe42f2f3ad3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX idx_77fe42f2727aca70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE TABLE str (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, source_locale VARCHAR(10) NOT NULL, source TEXT NOT NULL, context VARCHAR(80) DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT fk_77fe42f2727aca70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT fk_77fe42f2f3ad3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE file_asset DROP s3');
    }
}
