<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526193357 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, format VARCHAR(16) NOT NULL, size INT DEFAULT NULL, variant VARCHAR(32) DEFAULT NULL, music_xml TEXT DEFAULT NULL, lyrics_json JSON DEFAULT NULL, lyrics_text TEXT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, pending_steps JSON DEFAULT \'{}\' NOT NULL, file_asset_id INT NOT NULL, song_id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_187D3695B48A96DC ON audio (file_asset_id)');
        $this->addSql('CREATE INDEX IDX_187D3695A0BDB2F3 ON audio (song_id)');
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77FE42F2F3AD3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX IDX_77FE42F2727ACA70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE TABLE fetch_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, page_number INT NOT NULL, url VARCHAR(2048) NOT NULL, status VARCHAR(32) NOT NULL, content_type VARCHAR(255) DEFAULT NULL, accept VARCHAR(255) DEFAULT NULL, archive_path VARCHAR(2048) DEFAULT NULL, record_count INT DEFAULT NULL, error VARCHAR(1024) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_page ON fetch_page (provider_code, dataset_key, kind, page_number)');
        $this->addSql('CREATE TABLE fetch_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, row_number INT NOT NULL, source_id VARCHAR(255) DEFAULT NULL, record_type VARCHAR(32) DEFAULT NULL, payload TEXT NOT NULL, payload_bytes INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fetch_page_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB10B11C9F2FB857 ON fetch_record (fetch_page_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_record_page_row ON fetch_record (fetch_page_id, row_number)');
        $this->addSql('CREATE TABLE file_asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path TEXT NOT NULL, relative_path VARCHAR(512) NOT NULL, filename VARCHAR(255) NOT NULL, extension VARCHAR(16) NOT NULL, dirname VARCHAR(512) DEFAULT NULL, size INT DEFAULT NULL, modified_time INT DEFAULT NULL, is_readable BOOLEAN NOT NULL, type VARCHAR(32) NOT NULL, school VARCHAR(255) DEFAULT NULL, year INT DEFAULT NULL, mime_type VARCHAR(127) DEFAULT NULL, duration DOUBLE PRECISION DEFAULT NULL, probed_data JSONB DEFAULT NULL, lyrics_candidates JSON DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, pending_steps JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX file_asset_path ON file_asset (path)');
        $this->addSql('CREATE TABLE index_info (index_name VARCHAR(255) NOT NULL, last_indexed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_count INT NOT NULL, settings JSONB NOT NULL, task_id VARCHAR(255) DEFAULT NULL, primary_key VARCHAR(255) NOT NULL, batch_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, aggregator VARCHAR(255) DEFAULT NULL, institution VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) DEFAULT NULL, PRIMARY KEY (index_name))');
        $this->addSql('CREATE TABLE lyrics (code VARCHAR(255) NOT NULL, parent VARCHAR(255) DEFAULT NULL, file VARCHAR(255) DEFAULT NULL, text TEXT DEFAULT NULL, chord_pro_data JSONB DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE school (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(32) DEFAULT NULL, state VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE song (description TEXT DEFAULT NULL, date DATE DEFAULT NULL, year INT DEFAULT NULL, school VARCHAR(255) DEFAULT NULL, lyrics TEXT DEFAULT NULL, featured_artist TEXT DEFAULT NULL, recording_credits TEXT DEFAULT NULL, musicians TEXT DEFAULT NULL, writers TEXT DEFAULT NULL, wordpress_page_id INT DEFAULT NULL, recording TEXT DEFAULT NULL, publisher TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, aliases JSON DEFAULT NULL, lyrics_length INT DEFAULT NULL, id VARCHAR(255) NOT NULL, title TEXT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, pending_steps JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE song_lyrics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lyrics_text TEXT DEFAULT NULL, source_title VARCHAR(255) DEFAULT NULL, song_id VARCHAR(255) NOT NULL, file_asset_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DA17DECA0BDB2F3 ON song_lyrics (song_id)');
        $this->addSql('CREATE INDEX IDX_3DA17DECB48A96DC ON song_lyrics (file_asset_id)');
        $this->addSql('CREATE UNIQUE INDEX song_lyrics_unique ON song_lyrics (song_id, file_asset_id)');
        $this->addSql('CREATE TABLE storage_node (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, last_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_size INT DEFAULT NULL, dir_count INT DEFAULT NULL, file_count INT DEFAULT NULL, status VARCHAR(255) NOT NULL, meta JSON DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, is_dir BOOLEAN NOT NULL, is_public BOOLEAN NOT NULL, parent_id VARCHAR DEFAULT NULL, storage_id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C522350727ACA70 ON storage_node (parent_id)');
        $this->addSql('CREATE INDEX IDX_8C5223505CC5DB90 ON storage_node (storage_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORAGE_STORAGE_PATH ON storage_node (storage_id, path)');
        $this->addSql('CREATE TABLE storage_storage (adapter VARCHAR(255) DEFAULT NULL, root VARCHAR(255) DEFAULT NULL, id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, source_locale VARCHAR(10) NOT NULL, source TEXT NOT NULL, context VARCHAR(80) DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, identifiers JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE video (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, youtube_id VARCHAR(32) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, date DATE DEFAULT NULL, raw_data JSON DEFAULT NULL, thumbnail_url VARCHAR(255) DEFAULT NULL, thumbnails JSON DEFAULT NULL, year INT DEFAULT NULL, song_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CC7DA2CA0BDB2F3 ON video (song_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE audio ADD CONSTRAINT FK_187D3695B48A96DC FOREIGN KEY (file_asset_id) REFERENCES file_asset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audio ADD CONSTRAINT FK_187D3695A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2F3AD3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2727ACA70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fetch_record ADD CONSTRAINT FK_FB10B11C9F2FB857 FOREIGN KEY (fetch_page_id) REFERENCES fetch_page (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE song_lyrics ADD CONSTRAINT FK_3DA17DECA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE song_lyrics ADD CONSTRAINT FK_3DA17DECB48A96DC FOREIGN KEY (file_asset_id) REFERENCES file_asset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE storage_node ADD CONSTRAINT FK_8C522350727ACA70 FOREIGN KEY (parent_id) REFERENCES storage_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE storage_node ADD CONSTRAINT FK_8C5223505CC5DB90 FOREIGN KEY (storage_id) REFERENCES storage_storage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_7CC7DA2CA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audio DROP CONSTRAINT FK_187D3695B48A96DC');
        $this->addSql('ALTER TABLE audio DROP CONSTRAINT FK_187D3695A0BDB2F3');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2F3AD3475');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2727ACA70');
        $this->addSql('ALTER TABLE fetch_record DROP CONSTRAINT FK_FB10B11C9F2FB857');
        $this->addSql('ALTER TABLE song_lyrics DROP CONSTRAINT FK_3DA17DECA0BDB2F3');
        $this->addSql('ALTER TABLE song_lyrics DROP CONSTRAINT FK_3DA17DECB48A96DC');
        $this->addSql('ALTER TABLE storage_node DROP CONSTRAINT FK_8C522350727ACA70');
        $this->addSql('ALTER TABLE storage_node DROP CONSTRAINT FK_8C5223505CC5DB90');
        $this->addSql('ALTER TABLE video DROP CONSTRAINT FK_7CC7DA2CA0BDB2F3');
        $this->addSql('DROP TABLE audio');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE fetch_page');
        $this->addSql('DROP TABLE fetch_record');
        $this->addSql('DROP TABLE file_asset');
        $this->addSql('DROP TABLE index_info');
        $this->addSql('DROP TABLE lyrics');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE song');
        $this->addSql('DROP TABLE song_lyrics');
        $this->addSql('DROP TABLE storage_node');
        $this->addSql('DROP TABLE storage_storage');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE video');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
