# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  # these are the wordpress API keys
  api_username: '%env(API_USERNAME)%'
  api_password: '%env(API_PASSWORD)%'

#  youtube_api_key: '%env(YOUTUBE_API_KEY)%'
#  youtube_channel: UCt7IqS6nJWbJk6HByzJs5Tg # '%env(YOUTUBE_CHANNEL)%'
  router.request_context.scheme: 'https' # needed for oauth login?

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    Yectep\PhpSpreadsheetBundle\Factory:
#        alias: phpoffice.spreadsheet
